apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2
        image: api-2:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: API1_SERVICENAME
          value: http://api-1:9991/
