version: '2'

services: 
    nginx:
        image: nginx:1.19.9-alpine
        ports:
            - 19998:80
            - 443:443
        volumes:
            - ./apigateway.default.conf:/etc/nginx/conf.d/default.conf    

    api-1:
        build:
            context: ../src/api-1
        ports:
            - 9090:80

    api-2:
        build:
            context: ../src/api-2
        ports:
            - 9095:80
        environment:
            - API1_SERVICENAME="http://api-1/"