apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
spec:
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - name: api-1
        image: api-1:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
